name: validate
on:
  pull_request_target:
    types: [opened, synchronize]
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  authorize:
    if: github.repository != github.event.pull_request.head.repo.full_name
    environment:
      ${{ github.event_name == 'pull_request_target' &&
      github.event.pull_request.head.repo.full_name != github.repository &&
      'external' || 'internal' }}
    runs-on: ubuntu-latest
    steps:
      - run: echo ✓
  build:
    needs: authorize
    uses: ./.github/workflows/validate.yml
    secrets:
      ZRE_REPO_WITH_PAT: ${{ secrets.ZRE_REPO_WITH_PAT }}
